version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "bun run build:api && bun run dev:api"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./apps/hono-api/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "bun run build:sk && bun run dev:sk"
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
