<script lang="ts">
  import { Button, buttonVariants } from "$lib/components/ui/button";
  import { Sheet, SheetContent, SheetTrigger } from "$lib/components/ui/sheet";
  import { Menu } from "@lucide/svelte";
  import { page } from "$app/state";
  import * as AlertDialog from "$lib/components/ui/alert-dialog/index.js";

  // Define the navigation items
  const navItems = [{ label: "", href: "/" }];

  // Determine if a nav item is active
  let isActive = $derived((href: string) => page.url.pathname === href);

  // Toggle for mobile menu (optional usage)
  let isMobileMenuOpen = $state(false);
</script>

<header class="fixed top-0 z-50 w-full">
  <div class="container flex h-14 items-center mt-6">
    <!-- Logo -->
    <div class="mr-4 flex">
      <a href="/" class="flex items-center space-x-2">
        <span class="font-bold text-xl">Large Liar Model</span>
      </a>
    </div>

    <!-- Desktop Navigation -->
    <nav
      class="hidden md:flex items-center space-x-6 text-sm font-medium flex-1"
    >
      {#each navItems as { label, href }}
        <a
          {href}
          class={`transition-colors hover:text-foreground/80 ${
            isActive(href) ? "text-foreground" : "text-foreground/60"
          }`}
          aria-current={isActive(href) ? "page" : undefined}
        >
          {label}
        </a>
      {/each}
    </nav>

    <!-- Right Side Actions -->
    <div class="hidden md:flex items-center space-x-2">
      <AlertDialog.Root>
        <AlertDialog.Trigger class={buttonVariants({ variant: "link" })}>
          Instructions
        </AlertDialog.Trigger>
        <AlertDialog.Content>
          <AlertDialog.Header>
            <AlertDialog.Title>Instructions</AlertDialog.Title>
            <AlertDialog.Description>
              Welcome to Large Liar Model, a game that challenges your ability to separate fact from fiction in the age of AI. You'll encounter images, statistics, and news articles—some real, some generated by artificial intelligence. Your task? Decide which ones are genuine and which are artificial creations.

              Misinformation is everywhere, and AI is making it harder than ever to tell what’s real. Large Liar Model is a fun way to sharpen your critical thinking skills and become more media-savvy. Play, learn, and see if you can spot the truth!
            </AlertDialog.Description>
          </AlertDialog.Header>
          <AlertDialog.Footer>
            <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
          </AlertDialog.Footer>
        </AlertDialog.Content>
      </AlertDialog.Root>

      <AlertDialog.Root>
        <AlertDialog.Trigger class={buttonVariants({ variant: "link" })}>
          About
        </AlertDialog.Trigger>
        <AlertDialog.Content>
          <AlertDialog.Header>
            <AlertDialog.Title>About</AlertDialog.Title>
            <AlertDialog.Description>
              You’ll be presented with a series of images, statistics, and news articles.

              For each one, decide whether you think it’s real or AI-generated.

At the end of the game, you’ll see the correct answers and explanations.

Learn key insights on how to recognize AI-generated content and misinformation.

Take your time, think critically, and see how well you can navigate the world of truth and deception!
            </AlertDialog.Description>
          </AlertDialog.Header>
          <AlertDialog.Footer>
            <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
          </AlertDialog.Footer>
        </AlertDialog.Content>
      </AlertDialog.Root>
    </div>

    <!-- Mobile Menu Button -->
    <div class="flex md:hidden flex-1 justify-end">
      <Sheet bind:open={isMobileMenuOpen}>
        <SheetTrigger>
          {#snippet child(props)}
            <Button {...props} variant="ghost" size="icon" class="shrink-0">
              <Menu class="h-5 w-5" />
              <span class="sr-only">Open menu</span>
            </Button>
          {/snippet}
        </SheetTrigger>
        <SheetContent side="right" class="w-full max-w-xs sm:max-w-sm">
          <nav class="flex flex-col gap-4 mt-8">
            {#each navItems as { label, href }}
              <a
                {href}
                class={`text-lg font-medium transition-colors hover:text-foreground/80 ${
                  isActive(href) ? "text-foreground" : "text-foreground/60"
                }`}
                aria-current={isActive(href) ? "page" : undefined}
                onclick={() => (isMobileMenuOpen = false)}
              >
                {label}
              </a>
            {/each}
            <div class="flex flex-col space-y-2 mt-4">
              <Button variant="outline" href="/signin">Sign In</Button>
              <Button href="/signup">Sign Up</Button>
            </div>
          </nav>
        </SheetContent>
      </Sheet>
    </div>
  </div>
</header>
